# See:
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#default

gui:
  scrollHeight: 1
  expandFocusedSidePanel: true
  timeFormat: "2006-01-02 15:04"
  shortTimeFormat: "15:04"
  nerdFontsVersion: "3"
  branchColorPatterns:
    "^alpha$": cyan
    "^main$": cyan
    "^master$": cyan
    "^beta$": yellow
    "^production$": magenta
  theme:
    selectedLineBgColor:
      - white
    cherryPickedCommitBgColor:
      - black
    cherryPickedCommitFgColor:
      - green
  showDivergenceFromBaseBranch: arrowAndNumber
  showNumstatInFilesView: true
git:
  pagers:
    - pager: delta --paging=never
    - pager: delta --paging=never --side-by-side
    - pager: cat
  # The number of lines of context to show around each diff hunk. Can be changed
  # from within Lazygit with the `{` and `}` keys.
  diffContextSize: 10
customCommands:
  - key: "w"
    context: "files"
    command: "git wip"
    description: "Work In Progress"
  - key: "W"
    context: "files"
    command: "git wipp"
    description: "Work In Progress and push"
