# See:
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#default

gui:
  expandFocusedSidePanel: true
  timeFormat: "2006-01-02 15:04"
  shortTimeFormat: "15:04"
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - white
    cherryPickedCommitBgColor:
      - black
    cherryPickedCommitFgColor:
      - green
  showDivergenceFromBaseBranch: arrowAndNumber

git:
  paging:
    colorArg: always
    pager: delta --paging=never

customCommands:
  - key: "w"
    context: "files"
    command: "git wip"
    description: "Work In Progress"
  - key: "W"
    context: "files"
    command: "git wipp"
    description: "Work In Progress and push"
